version: '3.4'

services:
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb
    
  assets.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  users.api:
      environment:
      - ASPNETCORE_ENVIRONMENT=Development

  transactions.api:
      environment:
      - ASPNETCORE_ENVIRONMENT=Development